language: go
go:
  - 1.16.x
env:
  global:
  - GO111MODULE=on
  - TF_ACC=1
cache:
  directories:
  - $GOPATH/pkg/mod
  - $HOME/.cache/go-build
script:
  - make
deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/goreleaser.sh
    on:
      tags: true
      condition: "$TRAVIS_OS_NAME = linux"