package codeowners

import (
	"bytes"
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/liamg/go-github/github"
	"golang.org/x/crypto/openpgp"
)

type commitOptions struct {
	repoOwner     string
	repoName      string
	commitMessage string
	gpgPassphrase string
	gpgPrivateKey string // detached armor format
	changes       []github.TreeEntry
	branch        string
	username      string
	email         string
	retryCount    int
}

func createCommit(client *github.Client, options *commitOptions) error {

	ctx := context.Background()
	branch := options.branch

	if branch == "" {
		rep, _, err := client.Repositories.Get(ctx, options.repoOwner, options.repoName)
		if err != nil {
			return err
		}
		branch = *rep.DefaultBranch
	}

	// get ref for selected branch
	ref, _, err := client.Git.GetRef(ctx, options.repoOwner, options.repoName, "refs/heads/"+branch)
	if err != nil {
		return err
	}

	// create tree containing required changes
	tree, _, err := client.Git.CreateTree(ctx, options.repoOwner, options.repoName, *ref.Object.SHA, options.changes)
	if err != nil {
		return err
	}

	// get parent commit
	parent, _, err := client.Repositories.GetCommit(ctx, options.repoOwner, options.repoName, *ref.Object.SHA)
	if err != nil {
		return err
	}

	// This is not always populated, but is needed.
	parent.Commit.SHA = github.String(parent.GetSHA())

	date := time.Now()
	author := &github.CommitAuthor{
		Date:  &date,
		Name:  github.String(options.username),
		Email: github.String(options.email),
	}

	commit := &github.Commit{
		Author:  author,
		Message: &options.commitMessage,
		Tree:    tree,
		Parents: []github.Commit{*parent.Commit},
	}

	if options.gpgPrivateKey != "" {
		if err := signCommit(commit, options.gpgPrivateKey, options.gpgPassphrase); err != nil {
			return err
		}
	}

	newCommit, _, err := client.Git.CreateCommit(ctx, options.repoOwner, options.repoName, commit)
	if err != nil {
		return err
	}

	prBranch := &github.Reference{
		Ref: github.String(fmt.Sprintf("refs/heads/%s-%d", "codeowners", time.Now().UnixNano())),
		Object: &github.GitObject{
			SHA: newCommit.SHA,
		},
	}

	prRef, _, err := client.Git.CreateRef(ctx, options.repoOwner, options.repoName, prBranch)
	if err != nil {
		return err
	}

	pr, _, err := client.PullRequests.Create(ctx, options.repoOwner, options.repoName, &github.NewPullRequest{
		Title:               github.String(options.commitMessage),
		Head:                prBranch.Ref,
		Base:                github.String(branch),
		Body:                github.String("This PR was automatically generated by the CODEOWNERS terraform provider"),
		MaintainerCanModify: github.Bool(false),
	})
	if err != nil {
		return err
	}

	_, response, err := client.PullRequests.Merge(ctx, options.repoOwner, options.repoName, pr.GetNumber(), commit.GetMessage(), nil)
	if err != nil {

		pr.State = github.String("closed")
		_, _, _ = client.PullRequests.Edit(ctx, options.repoOwner, options.repoName, pr.GetNumber(), pr)

		if response == nil {
			return fmt.Errorf("failed to merge PR: %s", err)
		}

		// base branch was likely modified, try again
		if response.StatusCode == 405 && options.retryCount < 3 {
			options.retryCount++ // don't retry again
			return createCommit(client, options)
		}

		return fmt.Errorf("failed to merge PR: HTTP %d: %s", response.StatusCode, err)
	}

	// PR was merged, so we can attempt to remove our working branch (ignore failures, this isn't vital)
	_, _ = client.Git.DeleteRef(ctx, options.repoOwner, options.repoName, prRef.GetRef())

	return nil
}

func signCommit(commit *github.Commit, privateKey string, passphrase string) error {

	// the payload must be "an over the string commit as it would be written to the object database"
	// we sign this data to verify the commit
	payload := fmt.Sprintf(
		`tree %s
parent %s
author %s <%s> %d +0000
committer %s <%s> %d +0000

%s`,
		commit.Tree.GetSHA(),
		commit.Parents[0].GetSHA(),
		commit.Author.GetName(),
		commit.Author.GetEmail(),
		commit.Author.Date.Unix(),
		commit.Author.GetName(),
		commit.Author.GetEmail(),
		commit.Author.Date.Unix(),
		commit.GetMessage(),
	)

	// sign the payload data
	signature, err := createSignature(payload, privateKey, passphrase)
	if err != nil {
		return err
	}

	commit.Verification = &github.SignatureVerification{
		Signature: signature,
	}

	return nil
}

func createSignature(data string, privateKey string, passphrase string) (*string, error) {

	entityList, err := openpgp.ReadArmoredKeyRing(strings.NewReader(privateKey))
	if err != nil {
		return nil, err
	}

	pk := entityList[0]
	ppb := []byte(passphrase)

	if pk.PrivateKey != nil && pk.PrivateKey.Encrypted {
		err := pk.PrivateKey.Decrypt(ppb)
		if err != nil {
			return nil, err
		}
	}

	for _, subKey := range pk.Subkeys {
		if subKey.PrivateKey != nil && subKey.PrivateKey.Encrypted {
			err := subKey.PrivateKey.Decrypt(ppb)
			if err != nil {
				return nil, err
			}
		}
	}

	out := new(bytes.Buffer)
	reader := strings.NewReader(data)
	if err := openpgp.ArmoredDetachSign(out, pk, reader, nil); err != nil {
		return nil, err
	}

	signature := string(out.Bytes())
	return &signature, nil
}
